name: macOS Userspace Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    strategy:
      matrix:
        build_type: [Debug, Release]
        compiler:
          [{ cc: "clang", cxx: "clang++" }, { cc: "gcc-11", cxx: "g++-11" }]

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_C_COMPILER=${{ matrix.compiler.cc }} -DCMAKE_CXX_COMPILER=${{ matrix.compiler.cxx }}  -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} test

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{ matrix.build_type }}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{ matrix.build_type }}
